name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Viktigt för Pages + Actions
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pyyaml

      - name: Build index (generera docs/index.md)
        run: |
          python tools/build_index.py

      - name: Build MkDocs
        run: |
          mkdocs build --strict

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "site"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configure Pages (auto-enable)
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
